import test from 'node:test';
import assert from 'node:assert/strict';
import {escapeHtml,safeAssetPath,containedPath,validateWorks,validateContent,publicationErrors} from '../scripts/content.mjs';
import {localized,validateTranslations} from '../scripts/i18n.mjs';
import {loadContent} from '../scripts/load.mjs';
import {fileURLToPath} from 'node:url';
const data=await loadContent(fileURLToPath(new URL('../',import.meta.url)));
const text=(value)=>({en:value,'pt-BR':value});
const image={path:'assets/images/obras/test/01.webp',alt:text('Technical fixture, not real artwork'),width:800,height:1200};
const work=()=>({id:'fixture-test',title:text('Technical fixture'),year:'2000',technique:text('Test'),dimensions:'Test',status:'draft',cover:0,images:[structuredClone(image)]});
test('editorial HTML is escaped',()=>assert.equal(escapeHtml('<img onerror="x">'),'&lt;img onerror=&quot;x&quot;&gt;'));
test('approved relative asset path',()=>assert.equal(safeAssetPath(image.path),true));
test('traversal, URL and protocol relative paths rejected',()=>{for(const p of ['assets/images/../../secret.jpg','https://example.com/a.jpg','//host/a.jpg','assets/images/a/../b.jpg','assets/images//b.jpg'])assert.equal(safeAssetPath(p),false);});
test('file containment rejects traversal, absolute and backslash',()=>{for(const p of ['../secret','/secret','..\\secret'])assert.throws(()=>containedPath('/safe',p));});
test('empty works permitted in review phase',()=>assert.deepEqual(validateWorks([]),[]));
test('bilingual record valid',()=>assert.deepEqual(validateWorks([work()]),[]));
test('duplicate work ID rejected',()=>assert.ok(validateWorks([work(),work()]).some((x)=>x.includes('duplicate'))));
test('out-of-range cover rejected',()=>{const w=work();w.cover=4;assert.ok(validateWorks([w]).some((x)=>x.includes('cover')));});
test('missing English alt rejected',()=>{const w=work();delete w.images[0].alt.en;assert.ok(validateWorks([w]).some((x)=>x.includes('alt')));});
test('null work rejected without crash',()=>assert.ok(validateWorks([null]).length));
test('unknown record field rejected',()=>{const w=work();w.secret='private';assert.ok(validateWorks([w]).length);});
test('intrinsic media dimensions mandatory',()=>{const w=work();w.images[0].height=0;assert.ok(validateWorks([w]).length);});
test('no silent translation fallback',()=>assert.throws(()=>localized({'pt-BR':'texto'},'en')));
test('locale dictionary key parity',()=>assert.ok(validateTranslations({en:{a:'x'},'pt-BR':{b:'y'}}).length));
test('blank UI translation rejected',()=>assert.ok(validateTranslations({en:{a:'x'},'pt-BR':{a:''}}).length));
test('complete UI passes',()=>assert.deepEqual(validateTranslations(data.dictionaries),[]));
test('English is required at entrance',()=>{const d=structuredClone(data);d.site.defaultLocale='pt-BR';assert.ok(validateContent(d).length);});
test('invalid locale rejected',()=>assert.throws(()=>localized(text('x'),'es')));
test('canonical origin rejects credentials/query/path',()=>{for(const origin of ['http://example.com','https://a:b@example.com','https://example.com/x','https://example.com?x']){const d=structuredClone(data);d.site.origin=origin;assert.ok(validateContent(d).length);}});
test('base path rejects traversal and control characters',()=>{for(const basePath of ['/../','//','/bad\n/']){const d=structuredClone(data);d.site.basePath=basePath;assert.ok(validateContent(d).length);}});
test('release denied before content and approval',()=>assert.ok(publicationErrors(data).length>=4));
test('release denied without effective origin robots',()=>{const d=structuredClone(data);d.site.robotsRootVerified=false;assert.ok(publicationErrors(d).some((x)=>x.includes('origin root')));});
test('portrait missing EN translation rejected',()=>{const d=structuredClone(data);d.artist.portrait={...image,alt:{'pt-BR':'Retrato'}};assert.ok(validateContent(d).length);});
test('external video arbitrary provider rejected',()=>{const d=structuredClone(data);d.artist.featuredVideo={provider:'evil',id:'x',title:text('Test'),transcript:text('Test'),poster:image};assert.ok(validateContent(d).some((x)=>x.includes('provider')));});
